module.exports = {
  apps: [
    {
      name: 'voxproof-backend',
      cwd: '/home/phil/voxproof/backend',
      script: 'node',
      args: 'dist/index.js',
      watch: false,
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: '5s',
      env: {
        NODE_ENV: 'production',
      },
      error_file: '/home/phil/.pm2/logs/voxproof-backend-error.log',
      out_file: '/home/phil/.pm2/logs/voxproof-backend-out.log',
    },
    {
      name: 'voxproof-processor',
      cwd: '/home/phil/voxproof/processor',
      script: '/home/phil/voxproof/processor/venv/bin/uvicorn',
      args: 'main:app --host 0.0.0.0 --port 5000 --workers 4',
      watch: false,
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: '5s',
      interpreter: 'none',
      error_file: '/home/phil/.pm2/logs/voxproof-processor-error.log',
      out_file: '/home/phil/.pm2/logs/voxproof-processor-out.log',
    },
    {
      name: 'voxproof-frontend',
      cwd: '/home/phil/voxproof/frontend',
      script: 'node_modules/.bin/vite',
      args: '--host 0.0.0.0 --port 5174',
      watch: false,
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: '5s',
      error_file: '/home/phil/.pm2/logs/voxproof-frontend-error.log',
      out_file: '/home/phil/.pm2/logs/voxproof-frontend-out.log',
    },
  ],
}
