"""
PDF certificate generation for VoxProof vocal identity certification.
"""

import base64
import io
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle, HRFlowable
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont


# ─── Colors ─────────────────────────────────────────────────────────────────
INDIGO     = colors.HexColor('#4F46E5')
INDIGO_LIGHT = colors.HexColor('#EEF2FF')
GRAY_900   = colors.HexColor('#111827')
GRAY_600   = colors.HexColor('#4B5563')
GRAY_400   = colors.HexColor('#9CA3AF')
GRAY_200   = colors.HexColor('#E5E7EB')
WHITE      = colors.white

LANG_LABELS = {
    'fr': {
        'title': 'CERTIFICAT D\'IDENTITÉ VOCALE',
        'subtitle': 'Signature acoustique certifiée',
        'issued': 'Délivré le',
        'valid_until': 'Valide jusqu\'au',
        'holder': 'Titulaire',
        'hash_title': 'Empreinte acoustique blockchain',
        'hash_note': 'Ce hash SHA-256 est ancré de manière immuable sur la blockchain Avalanche.',
        'radar_title': 'Profil acoustique radar',
        'props_title': 'Propriétés acoustiques détaillées',
        'footer': 'Ce certificat a été généré par VoxProof — plateforme de certification vocale.',
        'tx': 'Transaction blockchain',
        'block': 'Bloc',
        'set': 'Ensemble de textes',
        'lang': 'Langue d\'enregistrement',
        'kyc': 'Vérification d\'identité',
        'kyc_yes': '✓ Identité vérifiée (Stripe Identity)',
        'kyc_no': '⚠ Identité NON vérifiée — certificat sans contrôle d\'identité',
    },
    'en': {
        'title': 'VOCAL IDENTITY CERTIFICATE',
        'subtitle': 'Certified acoustic signature',
        'issued': 'Issued on',
        'valid_until': 'Valid until',
        'holder': 'Holder',
        'hash_title': 'Blockchain acoustic fingerprint',
        'hash_note': 'This SHA-256 hash is immutably anchored on the Avalanche blockchain.',
        'radar_title': 'Acoustic radar profile',
        'props_title': 'Detailed acoustic properties',
        'footer': 'This certificate was generated by VoxProof — vocal certification platform.',
        'tx': 'Blockchain transaction',
        'block': 'Block',
        'set': 'Text set',
        'lang': 'Recording language',
        'kyc': 'Identity verification',
        'kyc_yes': '✓ Identity verified (Stripe Identity)',
        'kyc_no': '⚠ Identity NOT verified — certificate without identity check',
    },
    'es': {
        'title': 'CERTIFICADO DE IDENTIDAD VOCAL',
        'subtitle': 'Firma acústica certificada',
        'issued': 'Emitido el',
        'valid_until': 'Válido hasta',
        'holder': 'Titular',
        'hash_title': 'Huella acústica blockchain',
        'hash_note': 'Este hash SHA-256 está anclado de forma inmutable en la blockchain Avalanche.',
        'radar_title': 'Perfil acústico radar',
        'props_title': 'Propiedades acústicas detalladas',
        'footer': 'Este certificado fue generado por VoxProof — plataforma de certificación vocal.',
        'tx': 'Transacción blockchain',
        'block': 'Bloque',
        'set': 'Conjunto de textos',
        'lang': 'Idioma de grabación',
        'kyc': 'Verificación de identidad',
        'kyc_yes': '✓ Identidad verificada (Stripe Identity)',
        'kyc_no': '⚠ Identidad NO verificada — certificado sin control de identidad',
    },
}

SET_LABELS = {
    'fr': ['Identité & Présence', 'Nature & Éléments', 'Vie quotidienne', 'Pensée & Philosophie', 'Science & Technologie'],
    'en': ['Identity & Presence', 'Nature & Elements', 'Daily Life', 'Thought & Philosophy', 'Science & Technology'],
    'es': ['Identidad & Presencia', 'Naturaleza & Elementos', 'Vida cotidiana', 'Pensamiento & Filosofía', 'Ciencia & Tecnología'],
}


def generate_certificate(
    first_name: str,
    last_name: str,
    email: str,
    acoustic_hash: str,
    tx_hash: str,
    block_number: int,
    language: str,
    text_set_index: int,
    radar_b64: str,
    properties_b64: str,
    anchored_at: datetime,
    valid_until: datetime | None = None,
    kyc_verified: bool = True,
) -> bytes:
    """
    Generate a PDF certificate and return it as bytes.
    """
    lang = language if language in LANG_LABELS else 'fr'
    L = LANG_LABELS[lang]
    buf = io.BytesIO()

    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=20 * mm,
        bottomMargin=20 * mm,
    )

    styles = getSampleStyleSheet()
    story = []

    # ─── Header ─────────────────────────────────────────────────────────────
    title_style = ParagraphStyle(
        'CertTitle',
        fontSize=22,
        fontName='Helvetica-Bold',
        textColor=INDIGO,
        alignment=TA_CENTER,
        spaceAfter=4,
    )
    subtitle_style = ParagraphStyle(
        'CertSubtitle',
        fontSize=11,
        fontName='Helvetica',
        textColor=GRAY_600,
        alignment=TA_CENTER,
        spaceAfter=2,
    )

    story.append(Paragraph(L['title'], title_style))
    story.append(Spacer(1, 5 * mm))
    story.append(Paragraph(L['subtitle'], subtitle_style))
    story.append(HRFlowable(width='100%', thickness=2, color=INDIGO, spaceAfter=12))

    # ─── Identity block ──────────────────────────────────────────────────────
    info_style = ParagraphStyle('Info', fontSize=10, fontName='Helvetica', textColor=GRAY_600, spaceAfter=3)
    bold_style = ParagraphStyle('Bold', fontSize=11, fontName='Helvetica-Bold', textColor=GRAY_900, spaceAfter=3)
    kyc_ok_style = ParagraphStyle('KycOk', fontSize=10, fontName='Helvetica-Bold', textColor=colors.HexColor('#15803d'), spaceAfter=3)
    kyc_warn_style = ParagraphStyle('KycWarn', fontSize=10, fontName='Helvetica-Bold', textColor=colors.HexColor('#b45309'), spaceAfter=3)

    kyc_value = Paragraph(L['kyc_yes'], kyc_ok_style) if kyc_verified else Paragraph(L['kyc_no'], kyc_warn_style)

    identity_data = [
        [Paragraph(f"<b>{L['holder']}</b>", bold_style),
         Paragraph(f"{first_name} {last_name.upper()}", bold_style)],
        [Paragraph('Email', info_style), Paragraph(email, info_style)],
        [Paragraph(L['issued'], info_style),
         Paragraph(anchored_at.strftime('%d %B %Y à %H:%M UTC'), info_style)],
        [Paragraph(L['valid_until'], info_style),
         Paragraph(valid_until.strftime('%d %B %Y') if valid_until else '—', info_style)],
        [Paragraph(L['lang'], info_style),
         Paragraph({'fr': 'Français', 'en': 'English', 'es': 'Español'}.get(lang, lang), info_style)],
        [Paragraph(L['set'], info_style),
         Paragraph(f"{text_set_index + 1} — {SET_LABELS[lang][text_set_index]}", info_style)],
        [Paragraph(L['kyc'], info_style), kyc_value],
    ]

    id_table = Table(identity_data, colWidths=[55 * mm, 110 * mm])
    id_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), INDIGO_LIGHT),
        ('ROWBACKGROUNDS', (0, 0), (-1, -1), [INDIGO_LIGHT, WHITE]),
        ('BOX', (0, 0), (-1, -1), 0.5, GRAY_200),
        ('INNERGRID', (0, 0), (-1, -1), 0.3, GRAY_200),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    story.append(id_table)
    story.append(Spacer(1, 10 * mm))

    # ─── Hash block ──────────────────────────────────────────────────────────
    hash_title_style = ParagraphStyle('HashTitle', fontSize=12, fontName='Helvetica-Bold',
                                       textColor=GRAY_900, spaceAfter=4)
    hash_style = ParagraphStyle('Hash', fontSize=7.5, fontName='Courier-Bold',
                                 textColor=WHITE, backColor=GRAY_900,
                                 alignment=TA_CENTER, spaceAfter=4,
                                 leftIndent=4, rightIndent=4,
                                 borderPad=8, leading=14)
    note_style = ParagraphStyle('Note', fontSize=8, fontName='Helvetica',
                                 textColor=GRAY_600, alignment=TA_CENTER, spaceAfter=6)

    story.append(Paragraph(L['hash_title'], hash_title_style))

    # Hash displayed in a bordered box
    hash_table = Table([[Paragraph(acoustic_hash, hash_style)]], colWidths=[165 * mm])
    hash_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), GRAY_900),
        ('BOX', (0, 0), (-1, -1), 1.5, INDIGO),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(hash_table)
    story.append(Spacer(1, 2 * mm))
    story.append(Paragraph(L['hash_note'], note_style))

    # TX + Block
    tx_data = [
        [Paragraph(f"<b>{L['tx']}</b>", info_style), Paragraph(tx_hash[:42] + '...', info_style)],
        [Paragraph(f"<b>{L['block']}</b>", info_style), Paragraph(str(block_number), info_style)],
    ]
    tx_table = Table(tx_data, colWidths=[55 * mm, 110 * mm])
    tx_table.setStyle(TableStyle([
        ('ROWBACKGROUNDS', (0, 0), (-1, -1), [INDIGO_LIGHT, WHITE]),
        ('BOX', (0, 0), (-1, -1), 0.5, GRAY_200),
        ('INNERGRID', (0, 0), (-1, -1), 0.3, GRAY_200),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]))
    story.append(tx_table)
    story.append(Spacer(1, 8 * mm))

    # ─── Charts ──────────────────────────────────────────────────────────────
    chart_title_style = ParagraphStyle('ChartTitle', fontSize=11, fontName='Helvetica-Bold',
                                        textColor=GRAY_900, alignment=TA_CENTER, spaceAfter=4)

    def b64_to_image(b64: str, width_mm: float, height_mm: float) -> Image:
        img_bytes = base64.b64decode(b64)
        img_buf = io.BytesIO(img_bytes)
        return Image(img_buf, width=width_mm * mm, height=height_mm * mm)

    # Side by side charts
    radar_img = b64_to_image(radar_b64, 80, 80)
    props_img = b64_to_image(properties_b64, 85, 55)

    charts_data = [[
        [Paragraph(L['radar_title'], chart_title_style), radar_img],
        [Paragraph(L['props_title'], chart_title_style), props_img],
    ]]
    charts_table = Table([[radar_img, props_img]], colWidths=[85 * mm, 85 * mm])
    charts_table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('LEFTPADDING', (0, 0), (-1, -1), 2),
        ('RIGHTPADDING', (0, 0), (-1, -1), 2),
    ]))

    story.append(Paragraph(L['radar_title'] + '  |  ' + L['props_title'], chart_title_style))
    story.append(charts_table)
    story.append(Spacer(1, 8 * mm))

    # ─── Footer ──────────────────────────────────────────────────────────────
    story.append(HRFlowable(width='100%', thickness=1, color=GRAY_200, spaceAfter=6))
    footer_style = ParagraphStyle('Footer', fontSize=8, fontName='Helvetica',
                                   textColor=GRAY_400, alignment=TA_CENTER)
    story.append(Paragraph(L['footer'], footer_style))

    doc.build(story)
    return buf.getvalue()
